import type React from "react";

export const inp: React.CSSProperties = {
  background: "#f8fafc",
  border: "1px solid #e2e8f0",
  borderRadius: 10,
  padding: "10px 13px",
  color: "#0f172a",
  fontSize: 14,
  outline: "none",
  width: "100%",
  fontFamily: "'Inter', sans-serif",
  transition: "border-color .15s",
};

export const styles: Record<string, React.CSSProperties> = {
  header:      { display: "flex", alignItems: "flex-start", justifyContent: "space-between", marginBottom: 24 },
  title:       { fontSize: 22, fontWeight: 800, color: "#0f172a", marginBottom: 2, letterSpacing: "-0.4px" },
  sub:         { color: "#94a3b8", fontSize: 13, fontWeight: 500 },
  addBtn:      {
    display: "flex", alignItems: "center", gap: 8,
    background: "linear-gradient(135deg,#6366f1,#8b5cf6)",
    color: "#fff", border: "none", borderRadius: 11,
    padding: "11px 20px", fontSize: 14, fontWeight: 600,
    cursor: "pointer", boxShadow: "0 4px 14px rgba(99,102,241,.35)",
    whiteSpace: "nowrap",
    transition: "opacity .15s, transform .15s",
  },
  searchWrap:  {
    display: "flex", alignItems: "center", gap: 10,
    background: "#fff", border: "1px solid #e8edf4",
    borderRadius: 11, padding: "0 14px",
    flex: 1, maxWidth: 380,
    boxShadow: "0 1px 4px rgba(0,0,0,.04)",
  },
  searchInput: { flex: 1, background: "none", border: "none", outline: "none", color: "#0f172a", fontSize: 14, padding: "12px 0", fontFamily: "'Inter',sans-serif" },
  clearBtn:    { background: "none", border: "none", color: "#94a3b8", display: "flex", alignItems: "center", cursor: "pointer", padding: 2, borderRadius: 4 },
  grid:        { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(270px, 1fr))", gap: 20 },
  card:        { background: "#fff", border: "1px solid #e8edf4", borderRadius: 16, overflow: "hidden", cursor: "pointer", transition: "box-shadow .2s, transform .2s" },
  imgWrap:     { height: 180, background: "#f8fafc", display: "flex", alignItems: "center", justifyContent: "center", position: "relative", overflow: "hidden" },
  img:         { width: "100%", height: "100%", objectFit: "cover" },
  statusDot:   { position: "absolute", top: 10, right: 10, width: 8, height: 8, borderRadius: "50%" },
  cardBody:    { padding: "16px 18px" },
  cardCategory:{ fontSize: 10, color: "#94a3b8", textTransform: "uppercase", letterSpacing: "0.1em", marginBottom: 6, fontWeight: 600 },
  cardName:    { fontSize: 15, fontWeight: 700, color: "#0f172a", marginBottom: 4 },
  cardDesc:    { fontSize: 12.5, color: "#64748b", marginBottom: 14, overflow: "hidden", display: "-webkit-box", WebkitLineClamp: 2, WebkitBoxOrient: "vertical" },
  cardFooter:  { display: "flex", alignItems: "flex-end", justifyContent: "space-between" },
  price:       { fontSize: 17, fontWeight: 800, color: "#0f172a" },
  stock:       { fontSize: 12, color: "#94a3b8", marginTop: 2 },
  actions:     { display: "flex", gap: 7 },
  actionBtn:   { background: "#f8fafc", border: "1px solid #e8edf4", borderRadius: 8, padding: "7px 9px", color: "#64748b", display: "flex", alignItems: "center", cursor: "pointer", transition: "background .15s" },
  deleteBtn:   { color: "#ef4444", border: "1px solid #fee2e2", background: "#fff5f5" },
  empty:       { gridColumn: "1/-1", display: "flex", flexDirection: "column", alignItems: "center", gap: 14, padding: 72, color: "#94a3b8", fontSize: 14 },
  form:        { display: "flex", flexDirection: "column", gap: 16 },
  cancelBtn:   { background: "#f8fafc", border: "1px solid #e2e8f0", borderRadius: 10, padding: "10px 20px", color: "#475569", fontSize: 14, fontWeight: 500, cursor: "pointer" },
  saveBtn:     { background: "linear-gradient(135deg,#6366f1,#8b5cf6)", color: "#fff", border: "none", borderRadius: 10, padding: "10px 22px", fontSize: 14, fontWeight: 600, cursor: "pointer", boxShadow: "0 4px 14px rgba(99,102,241,.3)" },
};

export const mStyles: Record<string, React.CSSProperties> = {
  overlay:  { position: "fixed", inset: 0, background: "rgba(15,23,42,0.5)", backdropFilter: "blur(6px)", display: "flex", alignItems: "center", justifyContent: "center", zIndex: 100, padding: 20 },
  modal:    { background: "#fff", border: "1px solid #e8edf4", borderRadius: 20, width: "100%", maxWidth: 540, maxHeight: "90vh", overflowY: "auto", animation: "fadeIn .2s ease", boxShadow: "0 24px 64px rgba(0,0,0,.18)" },
  mHeader:  { display: "flex", alignItems: "center", justifyContent: "space-between", padding: "20px 24px 0" },
  mTitle:   { fontSize: 18, fontWeight: 700, color: "#0f172a" },
  closeBtn: { background: "#f1f5f9", border: "none", color: "#64748b", display: "flex", alignItems: "center", padding: 7, borderRadius: 8, cursor: "pointer", transition: "background .15s" },
};

export const dStyles: Record<string, React.CSSProperties> = {
  modal:         { background: "#fff", border: "1px solid #e8edf4", borderRadius: 22, width: "100%", maxWidth: 860, maxHeight: "90vh", overflowY: "auto", display: "flex", flexDirection: "row", animation: "fadeIn .22s ease", boxShadow: "0 32px 80px rgba(0,0,0,.2)" },
  imgPanel:      { width: 360, minWidth: 280, flexShrink: 0, background: "#f8fafc", borderRight: "1px solid #f1f5f9", borderRadius: "22px 0 0 22px", display: "flex", flexDirection: "column", overflow: "hidden", position: "relative" },
  mainImg:       { width: "100%", height: 300, objectFit: "cover", display: "block" },
  noImg:         { height: 300, display: "flex", alignItems: "center", justifyContent: "center", background: "#f1f5f9" },
  navBtn:        { position: "absolute", top: 132, background: "rgba(255,255,255,.9)", border: "1px solid #e8edf4", borderRadius: "50%", width: 32, height: 32, display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer", color: "#475569", zIndex: 2, boxShadow: "0 2px 8px rgba(0,0,0,.08)" },
  dots:          { position: "absolute", bottom: 0, left: 0, right: 0, display: "flex", justifyContent: "center", gap: 5, padding: "10px 0", background: "linear-gradient(to top, rgba(0,0,0,.15), transparent)" },
  dot:           { width: 6, height: 6, borderRadius: "50%", border: "none", cursor: "pointer", padding: 0, transition: "background .2s" },
  thumbRow:      { display: "flex", gap: 7, padding: "10px 14px", overflowX: "auto", borderTop: "1px solid #f1f5f9" },
  thumb:         { width: 54, height: 54, flexShrink: 0, borderRadius: 10, overflow: "hidden", border: "none", cursor: "pointer", padding: 0, outlineOffset: 2, transition: "outline .15s" },
  infoPanel:     { flex: 1, padding: "24px 26px", display: "flex", flexDirection: "column", gap: 18, overflowY: "auto" },
  infoHeader:    { display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: 12 },
  categoryBadge: { display: "inline-flex", alignItems: "center", gap: 5, fontSize: 10, fontWeight: 700, color: "#6366f1", textTransform: "uppercase", letterSpacing: "0.1em", background: "#eef2ff", padding: "3px 9px", borderRadius: 6, marginBottom: 8 },
  productName:   { fontSize: 21, fontWeight: 800, color: "#0f172a", lineHeight: 1.25, margin: 0, letterSpacing: "-0.3px" },
  statusRow:     { display: "flex", alignItems: "center" },
  statusBadge:   { display: "inline-flex", alignItems: "center", borderRadius: 20, padding: "4px 12px", fontSize: 12, fontWeight: 600 },
  metricsRow:    { display: "flex", gap: 12 },
  metricBox:     { flex: 1, background: "#f8fafc", border: "1px solid #e8edf4", borderRadius: 12, padding: "13px 16px" },
  metricLabel:   { fontSize: 10, color: "#94a3b8", fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.1em", marginBottom: 6 },
  metricValue:   { fontSize: 22, fontWeight: 800, color: "#0f172a" },
  outOfStock:    { fontSize: 12, fontWeight: 600, color: "#ef4444", marginLeft: 4 },
  descSection:   { background: "#f8fafc", borderRadius: 12, padding: "14px 16px", border: "1px solid #f1f5f9" },
  sectionLabel:  { display: "flex", alignItems: "center", fontSize: 10, fontWeight: 700, color: "#94a3b8", textTransform: "uppercase", letterSpacing: "0.1em", marginBottom: 9 },
  descText:      { fontSize: 14, color: "#475569", lineHeight: 1.65, margin: 0 },
  actionRow:     { display: "flex", gap: 10, marginTop: 4 },
  editBtn:       { flex: 1, display: "flex", alignItems: "center", justifyContent: "center", gap: 7, background: "linear-gradient(135deg,#6366f1,#8b5cf6)", color: "#fff", border: "none", borderRadius: 11, padding: "12px 0", fontSize: 14, fontWeight: 600, cursor: "pointer", boxShadow: "0 4px 14px rgba(99,102,241,.3)" },
  delBtn:        { display: "flex", alignItems: "center", justifyContent: "center", gap: 7, background: "#fff5f5", color: "#ef4444", border: "1px solid #fecaca", borderRadius: 11, padding: "12px 18px", fontSize: 14, fontWeight: 600, cursor: "pointer" },
};
